### PR TITLE
Professor classes

### PR DESCRIPTION
**Pull request by matssa**
This could be useful when creating the quizzes. Now they have a place to "come from".

### CODE REVIEW

**Comment by SindreSB** [comment]
Denne passerer ikke testene?

**Comment by SindreSB** [comment]
THe error was introduced when the seed function was added, before this branch was created. Delete the 0002 migration to make sure this passes. Test it on your computer first

**Comment by matssa** [comment]
Hmm, interessant. Kan jo prøve å slette den 0002 migration da og se om det går etterpå. Kan prøve det i morgen eller noe, da jeg ikke har tid i kveld.

**Comment by matssa** [comment]
Deleted 0002 migration. Works now. Also fixed an error in urls.

**Pull request merged**
